//! 反汇编渲染：对齐 V8 `--print-bytecode` / View8 反汇编器文本格式。
//!
//! 输出每函数形如（与 V8 printer 同形，便于与 `node --print-bytecode` 对拍）：
//! ```text
//! [generated bytecode for function: add (jscd <SharedFunctionInfo add>)]
//! Bytecode length: 6
//! Parameter count 3
//! Register count 0
//! Frame size 0
//! OSR nesting level: 0
//! Bytecode Age: 0
//!          0 @    0 : 0b 04              Ldar a1
//! Constant pool (size = 1)
//! Handler Table (size = 0)
//! Source Position Table (size = 7)
//! ```

use crate::bytecode::{Decoder, FamilyLayout, Instr, Operand};
use crate::serializer::{CodeCache, ObjId, Ref, SlotValue};
use crate::tables::VersionTable;
use std::fmt::Write as _;

/// 9.x 家族兜底槽位（表缺 layout 时使用）。
mod fallback_slots {
    /// SFI：function_data / name_or_scope_info / script
    pub const SFI_FUNCTION_DATA: usize = 1;
    pub const SFI_NAME: usize = 2;
    pub const SFI_SCRIPT: usize = 4;
    /// BCA：constant_pool / handler_table / source_position_table
    pub const BCA_CONSTANT_POOL: usize = 2;
    pub const BCA_HANDLER_TABLE: usize = 3;
    pub const BCA_SOURCE_POSITION_TABLE: usize = 4;
}

pub struct Disassembler<'a> {
    cache: &'a CodeCache,
    table: &'a VersionTable,
    layout: FamilyLayout,
    /// 源码占位字符串长度（attached ref 0 展示用，来自头部 source_hash）
    source_len: u32,
}

impl<'a> Disassembler<'a> {
    /// SFI 槽位：function_data（含 13.6 的 trusted/untrusted 拆分）。
    pub fn sfi_function_data_slots(&self) -> Vec<usize> {
        let ts = self.layout.tagged_size;
        if let Some(sfi) = &self.table.shared_function_info {
            let v: Vec<usize> = ["function_data", "trusted_function_data", "untrusted_function_data"]
                .iter()
                .filter_map(|n| sfi.slot(ts, n))
                .collect();
            if !v.is_empty() {
                return v;
            }
        }
        vec![fallback_slots::SFI_FUNCTION_DATA]
    }

    fn sfi_name_slot(&self) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .shared_function_info
            .as_ref()
            .and_then(|s| s.slot(ts, "name_or_scope_info"))
            .unwrap_or(fallback_slots::SFI_NAME)
    }

    fn sfi_script_slot(&self) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .shared_function_info
            .as_ref()
            .and_then(|s| s.slot_any(ts, &["script", "script_or_debug_info"]))
            .unwrap_or(fallback_slots::SFI_SCRIPT)
    }

    fn bca_slot(&self, names: &[&str], fallback: usize) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .bytecode_array
            .as_ref()
            .and_then(|b| b.fields.get(*names.first().unwrap()).copied().map(|o| o / ts))
            .or_else(|| {
                self.table
                    .bytecode_array
                    .as_ref()
                    .and_then(|b| names.iter().find_map(|n| b.fields.get(*n).copied().map(|o| o / ts)))
            })
            .unwrap_or(fallback)
    }

    fn bca_constant_pool_slot(&self) -> usize {
        self.bca_slot(&["constant_pool"], fallback_slots::BCA_CONSTANT_POOL)
    }
    fn bca_handler_table_slot(&self) -> usize {
        self.bca_slot(&["handler_table"], fallback_slots::BCA_HANDLER_TABLE)
    }
    fn bca_source_position_slot(&self) -> usize {
        self.bca_slot(&["source_position_table"], fallback_slots::BCA_SOURCE_POSITION_TABLE)
    }

    pub fn new(cache: &'a CodeCache, table: &'a VersionTable, layout: FamilyLayout) -> Self {
        Disassembler {
            cache,
            table,
            layout,
            source_len: 0,
        }
    }

    /// 渲染全部函数（按对象序 = 序列化序）。
    pub fn render_all(&self, filter: Option<&str>) -> Result<String, String> {
        let mut out = String::new();
        for id in 0..self.cache.objects.len() {
            if self.cache.obj(id).type_name != "SharedFunctionInfo" {
                continue;
            }
            let name = self.sfi_name(id);
            if let Some(f) = filter {
                if !name.contains(f) {
                    continue;
                }
            }
            self.render_sfi(id, &name, &mut out)?;
        }
        Ok(out)
    }

    /// 函数名。取值链对齐 V8 `SharedFunctionInfo::DebugName()`：
    /// name_or_scope_info 为 String 直接用；为 ScopeInfo 时读 FunctionName
    /// （function_variable_info.name），空则回落 inferred_function_name。
    pub fn sfi_name(&self, id: ObjId) -> String {
        let Some(SlotValue::Ref(r)) = self.cache.slot_at(id, self.sfi_name_slot()) else {
            return String::new();
        };
        match r {
            Ref::Object(sid) if self.cache.obj(*sid).type_name == "ScopeInfo" => {
                let name = self.scope_function_name(*sid);
                if name.is_empty() {
                    self.scope_inferred_name(*sid)
                } else {
                    name
                }
            }
            other => self.name_from_ref(*other),
        }
    }

    /// Ref → 名字字符串（String 对象 / 名字根）。
    fn name_from_ref(&self, r: Ref) -> String {
        match r {
            Ref::Object(sid) => {
                let o = self.cache.obj(sid);
                if o.type_name.contains("String") {
                    self.string_value(sid).unwrap_or_default()
                } else {
                    String::new()
                }
            }
            Ref::Root(i) => {
                let n = self.table.roots.get(i).cloned().unwrap_or_default();
                n.strip_prefix("String:").map(str::to_string).unwrap_or_default()
            }
            _ => String::new(),
        }
    }

    /// ScopeInfo 名字段位置（按版本布局逐段推进，返回 (function_name_slot, inferred_slot)）。
    ///
    /// 9.x–12.x：flags(Smi) | parameter_count | context_local_count | names[n] | infos[n] |
    ///           [saved] | [receiver] | [function_variable_info{name,index}] | [inferred] | ...
    /// 13.x：    flags(u32) + padding | parameter_count | context_local_count |
    ///           position_info(2) | [module_count] | names[n] (n<75) | [hashtable] | infos[n] |
    ///           [saved] | [function_variable_info] | [inferred] | ...
    fn scope_name_slots(&self, id: ObjId) -> (Option<usize>, Option<usize>) {
        let ts = self.layout.tagged_size;
        let cfg = self.table.scope_info.clone().unwrap_or(crate::tables::ScopeInfoLayout {
            flags_smi: true,
            position_info_early: false,
            max_inlined_names: 75,
            saved_class_bit: 10,
            function_variable_bits: [12, 13],
            receiver_bits: [7, 8],
            has_inferred_bit: 14,
        });
        let Some(flags_raw) = self.smi_slot(id, 1) else {
            return (None, None);
        };
        // flags：Smi 编码（值在高 32 位）或裸 uint32（低 32 位）
        let flags = if cfg.flags_smi {
            flags_raw as u32
        } else {
            self.cache
                .raw_at(id, ts, 4)
                .map(|d| u32::from_le_bytes(d.try_into().unwrap()))
                .unwrap_or(0)
        } as u64;

        let has_saved = (flags >> cfg.saved_class_bit) & 1 == 1;
        let function_var = ((flags >> cfg.function_variable_bits[0])
            & ((1 << (cfg.function_variable_bits[1] - cfg.function_variable_bits[0] + 1)) - 1))
            as u32;
        let has_inferred = (flags >> cfg.has_inferred_bit) & 1 == 1;
        let receiver_var = ((flags >> cfg.receiver_bits[0])
            & ((1 << (cfg.receiver_bits[1] - cfg.receiver_bits[0] + 1)) - 1)) as u32;
        let has_receiver = matches!(receiver_var, 1 | 2);

        if !cfg.position_info_early {
            // 9.x–12.x：槽位 = 4 + 2n + saved + receiver
            let Some(n) = self.smi_slot(id, 3) else {
                return (None, None);
            };
            let mut cursor = 4 + 2 * n as usize + has_saved as usize + has_receiver as usize;
            let function_name = if function_var != 0 {
                let slot = cursor;
                cursor += 2;
                Some(slot)
            } else {
                None
            };
            let inferred = if has_inferred { Some(cursor) } else { None };
            return (function_name, inferred);
        }

        // 13.x：flags+padding(ts+8) | parameter_count(ts+8) | context_local_count(ts+16)
        let param_off = ts + 8;
        let clc_off = ts + 16;
        let _ = param_off;
        let Some(n) = self
            .cache
            .raw_at(id, clc_off, ts)
            .and_then(|d| self.decode_smi_bytes(d))
        else {
            return (None, None);
        };
        let n = n as usize;
        let mut off = clc_off + ts; // 变长区起点（字节）
        off += 2 * ts; // position_info（2 个 Smi）
        let scope_type = flags & 0xF;
        if scope_type == 3 {
            off += ts; // module_variable_count
        }
        if n < cfg.max_inlined_names {
            off += n * ts; // context_local_names
        } else {
            off += ts; // context_local_names_hashtable
        }
        off += n * ts; // context_local_infos
        if has_saved {
            off += ts;
        }
        let function_name = if function_var != 0 {
            let slot = off / ts;
            off += 2 * ts;
            Some(slot)
        } else {
            None
        };
        let inferred = if has_inferred { Some(off / ts) } else { None };
        (function_name, inferred)
    }

    fn scope_function_name(&self, id: ObjId) -> String {
        match self.scope_name_slots(id).0 {
            Some(slot) => match self.cache.slot_at(id, slot) {
                Some(SlotValue::Ref(r)) => self.name_from_ref(*r),
                _ => String::new(),
            },
            None => String::new(),
        }
    }

    fn scope_inferred_name(&self, id: ObjId) -> String {
        match self.scope_name_slots(id).1 {
            Some(slot) => match self.cache.slot_at(id, slot) {
                Some(SlotValue::Ref(r)) => self.name_from_ref(*r),
                _ => String::new(),
            },
            None => String::new(),
        }
    }

    /// 解 8/4 字节 Smi（无压缩：值在高 32 位；压缩：低 32 位带 tag）。
    fn decode_smi_bytes(&self, d: &[u8]) -> Option<i64> {
        if d.len() == 8 {
            Some((read_u64(d) >> 32) as u32 as i32 as i64)
        } else if d.len() == 4 {
            let raw = u32::from_le_bytes(d.try_into().ok()?);
            if raw & 1 == 0 {
                None
            } else {
                Some(((raw as i32) >> 1) as i64)
            }
        } else {
            None
        }
    }

    /// 读对象内某个 tagged 槽的 Smi 值（无压缩：高 32 位；压缩：低 32 位带 tag）。
    fn smi_slot(&self, id: ObjId, slot: usize) -> Option<i64> {
        let ts = self.layout.tagged_size;
        let d = self.cache.raw_at(id, slot * ts, ts)?;
        if ts == 8 {
            Some((read_u64(d) >> 32) as u32 as i32 as i64)
        } else {
            let raw = u32::from_le_bytes(d.try_into().ok()?);
            Some(((raw as i32) >> 1) as i64)
        }
    }

    fn render_sfi(&self, id: ObjId, name: &str, out: &mut String) -> Result<(), String> {
        // function_data 槽（9.x–12.x 单槽；13.6 起 trusted/untrusted 拆分，取指向 BCA 的那个）
        let mut bca_id = None;
        for slot in self.sfi_function_data_slots() {
            if let Some(SlotValue::Ref(Ref::Object(b))) = self.cache.slot_at(id, slot) {
                if self.cache.obj(*b).type_name == "BytecodeArray" {
                    bca_id = Some(*b);
                    break;
                }
            }
        }
        let Some(bca_id) = bca_id else {
            return Ok(()); // 未编译（UncompiledData）——留给 functions 子命令展示
        };
        let ba_layout = self
            .table
            .bytecode_array
            .clone()
            .unwrap_or_else(|| crate::tables::BytecodeArrayLayout::fallback(self.layout.tagged_size));
        let header = ba_layout.header_size;
        let obj = self.cache.obj(bca_id);
        let bytecode_len = self
            .cache
            .raw_at(bca_id, self.layout.tagged_size, self.layout.tagged_size)
            .map(|d| read_u64(d) >> 32)
            .unwrap_or(0) as usize;
        let frame_size = ba_layout
            .off("frame_size")
            .and_then(|o| self.cache.raw_at(bca_id, o, 4))
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()))
            .unwrap_or(0);
        // parameter_size 是字节数；V8 的 parameter_count() = parameter_size / kSystemPointerSize
        let parameter_size = ba_layout
            .off("parameter_size")
            .and_then(|o| self.cache.raw_at(bca_id, o, 4))
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()) as i32)
            .unwrap_or(0);
        // parameter_size 语义随版本变：≤12 存字节数，13.x 起直接是计数
        let parameter_count = if self
            .table
            .parameter_count
            .map(|c| c.direct)
            .unwrap_or(false)
        {
            // 13.x：字段是 uint16，直接就是计数
            parameter_size & 0xFFFF
        } else {
            parameter_size / 8
        };
        // osr 字段名随版本变（osr_loop_nesting_level / osr_urgency_and_install_target）；11.3+ 已移除
        let osr = ba_layout
            .off("osr_loop_nesting_level")
            .or_else(|| ba_layout.off("osr_urgency_and_install_target"))
            .and_then(|o| self.cache.raw_at(bca_id, o, 1))
            .map(|d| d[0])
            .unwrap_or(0);
        let age = ba_layout
            .off("bytecode_age")
            .and_then(|o| self.cache.raw_at(bca_id, o, 1))
            .map(|d| d[0])
            .unwrap_or(0);
        let code = self
            .cache
            .raw_at(bca_id, header, bytecode_len)
            .unwrap_or_default();

        let decoder = Decoder::new(self.table, self.layout, parameter_count);
        let instrs = decoder.decode(code).map_err(|e| {
            format!("decode bytecode of '{}' ({} bytes): {e}", name, code.len())
        })?;
        // V8: register_count() = frame_size / kSystemPointerSize
        let register_count = frame_size / 8;

        let _ = writeln!(
            out,
            "[generated bytecode for function: {name} (jscd <SharedFunctionInfo {name}>)]"
        );
        let _ = writeln!(out, "Bytecode length: {bytecode_len}");
        let _ = writeln!(out, "Parameter count {parameter_count}");
        let _ = writeln!(out, "Register count {register_count}");
        let _ = writeln!(out, "Frame size {frame_size}");
        let _ = writeln!(out, "OSR nesting level: {osr}");
        let _ = writeln!(out, "Bytecode Age: {age}");
        for ins in &instrs {
            let hex = ins
                .bytes
                .iter()
                .map(|b| format!("{b:02x} "))
                .collect::<String>();
            let ops = ins
                .operands
                .iter()
                .map(|o| decoder.render_operand(o))
                .collect::<Vec<_>>()
                .join(", ");
            // 跳转目标：V8 打印 " (0xaddr @ target)"；我们无地址，用同样形状的 (jscd @ target)
            let jump = jump_target(&instrs, ins).map(|t| format!(" (jscd @ {t})")).unwrap_or_default();
            // switch 跳转表：{ case: @target, ... }（V8 BytecodeArray::Disassemble 同形）
            let switch = self
                .jump_table(bca_id, ins)
                .map(|entries| {
                    let body = entries
                        .iter()
                        .map(|(c, t)| format!(" {c}: @{t}"))
                        .collect::<Vec<_>>()
                        .join(",");
                    format!(" {{{body} }}")
                })
                .unwrap_or_default();
            let _ = writeln!(
                out,
                "{:>10} @ {:>4} : {:<18} {}{}{}{}",
                "",
                ins.offset,
                hex.trim_end(),
                ins.name,
                if ops.is_empty() { String::new() } else { format!(" {ops}") },
                jump,
                switch
            );
            let _ = &switch;
        }
        self.render_constant_pool(bca_id, out);
        self.render_byte_array(
            "Handler Table",
            self.cache.slot_at(bca_id, self.bca_handler_table_slot()).and_then(|v| v.as_ref()),
            out,
        );
        self.render_byte_array(
            "Source Position Table",
            self.cache
                .slot_at(bca_id, self.bca_source_position_slot())
                .and_then(|v| v.as_ref()),
            out,
        );
        let _ = writeln!(out);
        let _ = obj;
        Ok(())
    }

    fn render_byte_array(&self, label: &str, r: Option<Ref>, out: &mut String) {
        match r {
            Some(Ref::Object(id)) if self.cache.obj(id).type_name.contains("ByteArray") => {
                let len = self
                    .cache
                    .raw_at(
                        id,
                        self.layout.tagged_size,
                        self.layout.tagged_size,
                    )
                    .map(|d| read_u64(d) >> 32)
                    .unwrap_or(0);
                let _ = writeln!(out, "{label} (size = {len})");
            }
            Some(Ref::Root(i)) => {
                let n = self.table.roots.get(i).cloned().unwrap_or_default();
                if n.contains("empty_byte_array") || n.contains("EmptyByteArray") {
                    let _ = writeln!(out, "{label} (size = 0)");
                } else {
                    let _ = writeln!(out, "{label} (size = ?)");
                }
            }
            _ => {
                let _ = writeln!(out, "{label} (size = 0)");
            }
        }
    }

    fn render_constant_pool(&self, bca_id: ObjId, out: &mut String) {
        // 常量池：FixedArray（map + length Smi + elements，Smi 与指针交错在 raw/ref 单元里）
        let pool = self
            .cache
            .slot_at(bca_id, self.bca_constant_pool_slot())
            .and_then(|v| v.as_ref())
            .and_then(|r| self.cache.ref_object(r));
        let Some(pool_id) = pool else {
            let _ = writeln!(out, "Constant pool (size = 0)");
            return;
        };
        let entries = self.fixed_array_entries(pool_id);
        let _ = writeln!(out, "Constant pool (size = {})", entries.len());
        for (i, e) in entries.iter().enumerate() {
            let _ = writeln!(out, "{:>12}: {}", i, e);
        }
    }

    /// switch 跳转表：常量池 [start, start+size) 的 Smi 项，目标 = 指令偏移 + Smi。
    fn jump_table(&self, bca_id: ObjId, ins: &Instr) -> Option<Vec<(i32, usize)>> {
        // SwitchOnSmiNoFeedback: [Idx table_start, UImm size, Imm case_base]
        // SwitchOnGeneratorState: [Reg, Idx table_start, UImm size]，case_base = 0
        let (start_idx, size_idx, base_idx, base_fixed) = match ins.name.as_str() {
            "SwitchOnSmiNoFeedback" => (0usize, 1usize, Some(2usize), 0i32),
            "SwitchOnGeneratorState" => (1, 2, None, 0),
            _ => return None,
        };
        let table_start = match ins.operands.get(start_idx)? {
            Operand::Idx(v) => *v as usize,
            _ => return None,
        };
        let table_size = match ins.operands.get(size_idx)? {
            Operand::Idx(v) => *v as usize,
            Operand::Imm(v) => *v as usize,
            _ => return None,
        };
        let case_base = match base_idx {
            Some(i) => match ins.operands.get(i)? {
                Operand::Imm(v) => *v as i32,
                Operand::Idx(v) => *v as i32,
                _ => return None,
            },
            None => base_fixed,
        };
        let pool = self
            .cache
            .slot_at(bca_id, self.bca_constant_pool_slot())
            .and_then(|v| v.as_ref())
            .and_then(|r| self.cache.ref_object(r))?;
        let mut out = Vec::new();
        for i in 0..table_size {
            // V8 迭代器跳过非 Smi 槽，但 case 值随槽位递增
            if let Some(ArrayElem::Smi(v)) = self.array_elem(pool, table_start + i) {
                out.push((case_base + i as i32, ins.offset + v as usize));
            }
        }
        Some(out)
    }

    /// 供 CLI 使用的公开入口。
    pub fn array_elem_public(&self, id: ObjId, index: usize) -> Option<ArrayElem> {
        self.array_elem(id, index)
    }

    /// parameter_count 是否直接是计数（13.x+）。
    pub fn parameter_count_direct(&self) -> bool {
        self.table.parameter_count.map(|c| c.direct).unwrap_or(false)
    }

    /// FixedArray 元素（按字节偏移取值；length 槽在 offset=ts，元素 i 在 (2+i)*ts）。
    fn array_elem(&self, id: ObjId, index: usize) -> Option<ArrayElem> {
        let off = (2 + index) * self.layout.tagged_size;
        self.value_at_byte_offset(id, off)
    }

    /// 对象内某字节偏移处的槽值：指针槽 → Ref；raw 块内 → Smi/字节。
    fn value_at_byte_offset(&self, id: ObjId, byte_off: usize) -> Option<ArrayElem> {
        let ts = self.layout.tagged_size;
        for s in &self.cache.obj(id).slots {
            match &s.value {
                SlotValue::Ref(r) => {
                    if s.index * ts == byte_off {
                        return Some(ArrayElem::Ref(*r));
                    }
                }
                SlotValue::Raw(d) => {
                    let start = s.index * ts;
                    if byte_off >= start && byte_off + ts <= start + d.len() {
                        let rel = byte_off - start;
                        return Some(match decode_smi(&d[rel..rel + ts]) {
                            Some(v) => ArrayElem::Smi(v),
                            None => ArrayElem::Bytes(d[rel..rel + ts].to_vec()),
                        });
                    }
                }
                SlotValue::Repeat(n, inner) => {
                    let start = s.index * ts;
                    if byte_off >= start && byte_off < start + n * ts {
                        return match inner.as_ref() {
                            SlotValue::Ref(r) => Some(ArrayElem::Ref(*r)),
                            SlotValue::Raw(d) => decode_smi(d).map(ArrayElem::Smi),
                            _ => None,
                        };
                    }
                }
                _ => {}
            }
        }
        None
    }

    /// FixedArray 元素数（length 槽 = Smi）。
    pub fn fixed_array_len(&self, id: ObjId) -> usize {
        let ts = self.layout.tagged_size;
        self.cache
            .raw_at(id, ts, 4)
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()) as usize)
            .unwrap_or(0)
    }

    /// FixedArray 元素展开（Smi / 引用，按元素序）。
    pub fn fixed_array_entries(&self, id: ObjId) -> Vec<String> {
        let len = self.fixed_array_len(id);
        (0..len)
            .map(|i| match self.array_elem(id, i) {
                Some(ArrayElem::Smi(v)) => v.to_string(),
                Some(ArrayElem::Ref(r)) => self.describe_ref(&r),
                Some(ArrayElem::Bytes(b)) => format!("<raw {}>", hex(&b)),
                None => "<hole>".into(),
            })
            .collect()
    }

    /// FixedArray 的数值元素（Smi → Some，其余 → None），用于跳转表。
    pub fn fixed_array_smis(&self, id: ObjId) -> Vec<Option<i64>> {
        let len = self.fixed_array_len(id);
        (0..len)
            .map(|i| match self.array_elem(id, i) {
                Some(ArrayElem::Smi(v)) => Some(v),
                _ => None,
            })
            .collect()
    }

    /// 引用 → 可读描述（对齐 V8 printer 的常量池样式）。
    pub fn describe_ref(&self, r: &Ref) -> String {
        match r {
            Ref::Object(id) => {
                let o = self.cache.obj(*id);
                match o.type_name.as_str() {
                    t if t.contains("String") => self
                        .string_value(*id)
                        .map(|s| format!("<String[{}]: #{} >", s.chars().count(), s))
                        .unwrap_or_else(|| "<String>".into()),
                    "SharedFunctionInfo" => {
                        format!("<SharedFunctionInfo {}>", self.sfi_name(*id))
                    }
                    "HeapNumber" => {
                        let v = self
                            .cache
                            .raw_at(*id, self.layout.tagged_size, 8)
                            .map(|d| f64::from_le_bytes(d.try_into().unwrap()))
                            .unwrap_or(f64::NAN);
                        format!("<HeapNumber {v}>")
                    }
                    "ScopeInfo" => "<ScopeInfo>".into(),
                    "FixedArray" | "FixedCOWArray" => format!("<FixedArray[{}]>", self.fixed_array_entries(*id).len()),
                    "ObjectBoilerplateDescription" => "<ObjectBoilerplateDescription>".into(),
                    "ArrayBoilerplateDescription" => "<ArrayBoilerplateDescription>".into(),
                    "ByteArray" | "EmptyByteArray" => "<ByteArray>".into(),
                    "BigInt" => self
                        .bigint_value(*id)
                        .map(|v| format!("<BigInt {v}>"))
                        .unwrap_or_else(|| "<BigInt>".into()),
                    other => format!("<{other}>"),
                }
            }
            Ref::Root(i) => {
                let name = self
                    .table
                    .roots
                    .get(*i)
                    .cloned()
                    .unwrap_or_else(|| format!("root#{i}"));
                match name.as_str() {
                    n if n.starts_with("String:") => format!("<String: {}>", &n[7..]),
                    n if n.starts_with("Symbol:") => format!("<Symbol: {}>", &n[7..]),
                    "undefined_value" => "<undefined>".into(),
                    "null_value" => "<null>".into(),
                    "true_value" => "<true>".into(),
                    "false_value" => "<false>".into(),
                    "the_hole_value" => "<the_hole>".into(),
                    "uninitialized_value" => "<uninitialized>".into(),
                    "empty_fixed_array" => "<EmptyFixedArray>".into(),
                    "empty_string" => "<String[0]: #>".into(),
                    other => format!("<{other}>"),
                }
            }
            Ref::Attached(0) => {
                let len = self.attached_source_len();
                format!("<String[{len}]: #(source placeholder)>")
            }
            Ref::Attached(i) => format!("<Attached({i})>"),
            Ref::RoRef(c, o) => format!("<ro:{c}/{o}>"),
        }
    }

    /// 源码占位字符串长度（来自头部 source_hash，由调用方注入）
    fn attached_source_len(&self) -> u32 {
        self.source_len
    }

    pub fn string_value(&self, id: ObjId) -> Option<String> {
        let obj = self.cache.obj(id);
        // 字符串布局（真机实证，含压缩/非压缩家族一致）：
        //   @0 map | @8 hash_field(int32) | @12 length(int32) | @16 chars
        let length = self
            .cache
            .raw_at(id, 12, 4)
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()) as usize)?;
        let is_one_byte = obj.type_name.contains("OneByte");
        let chars_off = 16;
        let d = self.cache.raw_at(id, chars_off, length)?;
        if is_one_byte {
            Some(String::from_utf8_lossy(d).into_owned())
        } else {
            let u16s: Vec<u16> = d
                .chunks(2)
                .map(|c| u16::from_le_bytes([c[0], *c.get(1).unwrap_or(&0)]))
                .collect();
            Some(String::from_utf16_lossy(&u16s))
        }
    }

    fn bigint_value(&self, id: ObjId) -> Option<String> {
        // BigInt：map + length(Smi) + 数字（64 位块，补码）
        let ts = self.layout.tagged_size;
        let len = self
            .cache
            .raw_at(id, ts, ts)
            .map(|d| read_u64(d) >> 32)? as usize;
        if len == 0 {
            return Some("0".into());
        }
        let bytes = self.cache.raw_at(id, 2 * ts, len * 8)?;
        let mut v: i128 = 0;
        for (i, chunk) in bytes.chunks(8).enumerate() {
            let word = u64::from_le_bytes(chunk.try_into().ok()?);
            v |= (word as i128) << (64 * i);
        }
        // 最高位为符号位
        let bits = len * 64;
        if bits < 128 && (v >> (bits - 1)) & 1 == 1 {
            v -= 1i128 << bits;
        }
        Some(v.to_string())
    }

    /// 供 CLI 注入源码长度（attached ref 0 的展示）
    pub fn with_source_len(mut self, len: u32) -> Self {
        self.source_len = len;
        self
    }
}

/// 跳转目标：IsJumpImmediate → 下一条指令偏移 + 无符号立即数（JumpLoop 取负）；
/// IsJumpConstant → 常量池里的 Smi。返回绝对偏移（对齐 GetJumpTargetOffset）。
fn jump_target(instrs: &[Instr], ins: &Instr) -> Option<usize> {
    // V8 BytecodeArrayIterator::GetJumpTargetOffset() = GetAbsoluteOffset(relative)
    // = 指令自身偏移 + 相对量（不是下一条指令）。JumpLoop 的相对量取负。
    let here = ins.offset;
    match ins.name.as_str() {
        "Jump" | "JumpIfTrue" | "JumpIfFalse" | "JumpIfToBooleanTrue"
        | "JumpIfToBooleanFalse" | "JumpIfNull" | "JumpIfNotNull" | "JumpIfUndefined"
        | "JumpIfUndefinedOrNull" | "JumpIfNotUndefined" | "JumpIfJSReceiver"
        | "JumpIfNotHole" | "JumpIfReferenceError" | "JumpIfNotReferenceError" => {
            let rel = match ins.operands.first()? {
                Operand::Idx(v) => *v as usize,
                Operand::Imm(v) => *v as usize,
                _ => return None,
            };
            Some(here + rel)
        }
        "JumpLoop" => {
            let rel = match ins.operands.first()? {
                Operand::Idx(v) => *v as usize,
                Operand::Imm(v) => *v as usize,
                _ => return None,
            };
            here.checked_sub(rel)
        }
        _ => {
            let _ = instrs;
            None
        }
    }
}

/// FixedArray 元素形态。
#[derive(Debug, Clone)]
pub enum ArrayElem {
    Ref(Ref),
    Smi(i64),
    Bytes(Vec<u8>),
}

fn read_u64(d: &[u8]) -> u64 {
    let mut v = 0u64;
    for (i, b) in d.iter().take(8).enumerate() {
        v |= (*b as u64) << (8 * i);
    }
    v
}

/// Smi 解码：无压缩（ts=8）值在高 32 位；压缩（ts=4）值在低 32 位且末位为 1。
fn decode_smi(group: &[u8]) -> Option<i64> {
    if group.len() == 8 {
        let raw = read_u64(group);
        let v = (raw >> 32) as u32;
        if v == 0 && raw != 0 {
            return None;
        }
        Some((v as i32) as i64)
    } else if group.len() == 4 {
        let raw = u32::from_le_bytes(group.try_into().ok()?);
        if raw & 1 == 0 {
            return None;
        }
        Some(((raw as i32) >> 1) as i64)
    } else {
        None
    }
}

fn hex(d: &[u8]) -> String {
    d.iter().map(|b| format!("{b:02x}")).collect::<Vec<_>>().join("")
}

#[allow(dead_code)]
fn max_register(instrs: &[Instr]) -> Option<i32> {
    let mut max: Option<i32> = None;
    for ins in instrs {
        for op in &ins.operands {
            let idx = match op {
                Operand::Reg(i) => Some(*i),
                Operand::RegList { first, count } => Some(if *count > 0 {
                    first + (*count as i32) - 1
                } else {
                    *first
                }),
                _ => None,
            };
            if let Some(i) = idx {
                if i >= 0 {
                    max = Some(max.map_or(i, |m: i32| m.max(i)));
                }
            }
        }
    }
    max
}