//! 反汇编渲染：对齐 V8 `--print-bytecode` / View8 反汇编器文本格式。
//!
//! 输出每函数形如（与 V8 printer 同形，便于与 `node --print-bytecode` 对拍）：
//! ```text
//! [generated bytecode for function: add (jscd <SharedFunctionInfo add>)]
//! Bytecode length: 6
//! Parameter count 3
//! Register count 0
//! Frame size 0
//! OSR nesting level: 0
//! Bytecode Age: 0
//!          0 @    0 : 0b 04              Ldar a1
//! Constant pool (size = 1)
//! Handler Table (size = 0)
//! Source Position Table (size = 7)
//! ```

use crate::bytecode::{Decoder, FamilyLayout, Instr, Operand};
use crate::serializer::{CodeCache, Elem, ObjId, Ref, SlotValue};
use crate::tables::VersionTable;
use std::fmt::Write as _;

/// 9.x 家族兜底槽位（表缺 layout 时使用）。
mod fallback_slots {
    /// SFI：function_data / name_or_scope_info / script
    pub const SFI_FUNCTION_DATA: usize = 1;
    pub const SFI_NAME: usize = 2;
    pub const SFI_SCRIPT: usize = 4;
    /// BCA：constant_pool / handler_table / source_position_table
    pub const BCA_CONSTANT_POOL: usize = 2;
    pub const BCA_HANDLER_TABLE: usize = 3;
    pub const BCA_SOURCE_POSITION_TABLE: usize = 4;
}

pub struct Disassembler<'a> {
    cache: &'a CodeCache<'a>,
    table: &'a VersionTable,
    layout: FamilyLayout,
    /// 源码占位字符串长度（attached ref 0 展示用，来自头部 source_hash）
    source_len: u32,
    /// 只读堆名表：13.x 起函数名/属性名常以 `ro{chunk}/{offset}` 引用出现，
    /// 没有它只能回落成空字符串（node24 的 `count` 因此成了匿名函数，
    /// 调用点 `count(...)` 找的是全局名 → 生成器 fixture 全空）
    ro_map: Option<std::rc::Rc<crate::decompile::RoMap>>,
}

impl<'a> Disassembler<'a> {
    /// SFI 槽位：function_data（含 13.6 的 trusted/untrusted 拆分）。
    pub fn sfi_function_data_slots(&self) -> Vec<usize> {
        let ts = self.layout.tagged_size;
        if let Some(sfi) = &self.table.shared_function_info {
            let v: Vec<usize> = ["function_data", "trusted_function_data", "untrusted_function_data"]
                .iter()
                .filter_map(|n| sfi.slot(ts, n))
                .collect();
            if !v.is_empty() {
                return v;
            }
        }
        vec![fallback_slots::SFI_FUNCTION_DATA]
    }

    pub fn sfi_name_slot(&self) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .shared_function_info
            .as_ref()
            .and_then(|s| s.slot(ts, "name_or_scope_info"))
            .unwrap_or(fallback_slots::SFI_NAME)
    }

    fn sfi_script_slot(&self) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .shared_function_info
            .as_ref()
            .and_then(|s| s.slot_any(ts, &["script", "script_or_debug_info"]))
            .unwrap_or(fallback_slots::SFI_SCRIPT)
    }

    fn bca_slot(&self, names: &[&str], fallback: usize) -> usize {
        let ts = self.layout.tagged_size;
        self.table
            .bytecode_array
            .as_ref()
            .and_then(|b| b.fields.get(*names.first().unwrap()).copied().map(|o| o / ts))
            .or_else(|| {
                self.table
                    .bytecode_array
                    .as_ref()
                    .and_then(|b| names.iter().find_map(|n| b.fields.get(*n).copied().map(|o| o / ts)))
            })
            .unwrap_or(fallback)
    }

    pub fn bca_constant_pool_slot(&self) -> usize {
        self.bca_slot(&["constant_pool"], fallback_slots::BCA_CONSTANT_POOL)
    }
    pub fn bca_handler_table_slot(&self) -> usize {
        self.bca_slot(&["handler_table"], fallback_slots::BCA_HANDLER_TABLE)
    }
    pub fn bca_source_position_slot(&self) -> usize {
        self.bca_slot(&["source_position_table"], fallback_slots::BCA_SOURCE_POSITION_TABLE)
    }

    pub fn new(cache: &'a CodeCache<'a>, table: &'a VersionTable, layout: FamilyLayout) -> Self {
        Disassembler {
            cache,
            table,
            layout,
            source_len: 0,
            ro_map: None,
        }
    }

    /// 附上只读堆名表（`--ro-map`）。
    pub fn with_ro_map(mut self, m: Option<std::rc::Rc<crate::decompile::RoMap>>) -> Self {
        self.ro_map = m;
        self
    }

    /// 渲染全部函数（按对象序 = 序列化序）。
    pub fn render_all(&self, filter: Option<&str>) -> Result<String, String> {
        let mut out = String::new();
        for id in 0..self.cache.objects.len() {
            if !self.cache.obj(id).ty.is(self.table, "SharedFunctionInfo") {
                continue;
            }
            let name = self.sfi_name(id);
            if let Some(f) = filter {
                if !name.contains(f) {
                    continue;
                }
            }
            self.render_sfi(id, &name, &mut out)?;
        }
        Ok(out)
    }

    /// 函数名。取值链对齐 V8 `SharedFunctionInfo::DebugName()`：
    /// name_or_scope_info 为 String 直接用；为 ScopeInfo 时读 FunctionName
    /// （function_variable_info.name），空则回落 inferred_function_name。
    pub fn sfi_name(&self, id: ObjId) -> String {
        if std::env::var("JSCD_DBG_SFI").is_ok() {
            let n = self.cache.array_len(id).max(16);
            let mut out = Vec::new();
            for i in 0..n.min(16) {
                out.push(match self.cache.slot_at(id, i) {
                    Some(SlotValue::Ref(r)) => format!("{i}:{}", self.describe_ref(r)),
                    Some(other) => format!("{i}:{other:?}"),
                    None => format!("{i}:-"),
                });
            }
            eprintln!(
                "[sfi] id={id} name_slot={} slots={out:?}",
                self.sfi_name_slot()
            );
        }
        let Some(SlotValue::Ref(r)) = self.cache.slot_at(id, self.sfi_name_slot()) else {
            return String::new();
        };
        match r {
            Ref::Object(sid) if self.cache.obj(*sid).ty.is(self.table, "ScopeInfo") => {
                let name = self.scope_function_name(*sid);
                if name.is_empty() {
                    self.scope_inferred_name(*sid)
                } else {
                    name
                }
            }
            other => self.name_from_ref(*other),
        }
    }

    /// Ref → 名字字符串（String 对象 / 名字根）。
    fn name_from_ref(&self, r: Ref) -> String {
        match r {
            Ref::Object(sid) => {
                let o = self.cache.obj(sid);
                if o.ty.is_string(self.table) {
                    self.string_value(sid).unwrap_or_default()
                } else {
                    String::new()
                }
            }
            Ref::Root(i) => {
                let n = self.table.root_name(i).unwrap_or_default().to_string();
                n.strip_prefix("String:").map(str::to_string).unwrap_or_default()
            }
            Ref::RoRef(c, off) => self
                .ro_map
                .as_deref()
                .and_then(|m| m.get(c, off))
                .map(str::to_string)
                .unwrap_or_default(),
            _ => String::new(),
        }
    }

    /// ScopeInfo 名字段位置（按版本布局逐段推进，返回 (function_name_slot, inferred_slot)）。
    ///
    /// 9.x–12.x：flags(Smi) | parameter_count | context_local_count | names[n] | infos[n] |
    ///           [saved] | [receiver] | [function_variable_info{name,index}] | [inferred] | ...
    /// 13.x：    flags(u32) + padding | parameter_count | context_local_count |
    ///           position_info(2) | [module_count] | names[n] (n<75) | [hashtable] | infos[n] |
    ///           [saved] | [function_variable_info] | [inferred] | ...
    /// ScopeInfo 数值域（Flags/ParameterCount/ContextLocalCount，各占一个 slot）。
    ///
    /// 存储形态随版本变：9.x–12.x 是 Smi（值在高 32 位），13.x 是裸 int32（低 32 位）。
    /// ≤8.4 的 accessor 是 `FOR_EACH_SCOPE_INFO_NUMERIC_FIELD` 宏生成的
    /// （scope-info.cc 里 `Smi::ToInt(get(...))`），codegen 没认出来、表里标了
    /// `flags_smi: false` —— 实测读低 4 字节恒为 0，于是 flags/形参名全丢。
    /// 这里自适应：低 4 字节为 0 而 Smi 半边非 0 → 说明其实是 Smi 存储。
    fn num_field(&self, id: ObjId, slot: usize, flags_smi: bool) -> Option<u32> {
        let raw = self
            .cache
            .raw_at(id, slot * self.layout.tagged_size, 4)
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()));
        let smi = self.smi_slot(id, slot).map(|v| v as u32);
        match (flags_smi, raw, smi) {
            (true, _, Some(s)) => Some(s),
            (false, Some(0), Some(s)) if s != 0 => Some(s),
            (false, Some(r), _) => Some(r),
            (_, _, s) => s.or(raw),
        }
    }

    fn scope_name_slots(&self, id: ObjId) -> (Option<usize>, Option<usize>) {
        let ts = self.layout.tagged_size;
        let cfg = self.table.scope_info.clone().unwrap_or(crate::tables::ScopeInfoLayout {
            flags_smi: true,
            position_info_early: false,
            max_inlined_names: 75,
            saved_class_bit: 10,
            function_variable_bits: [12, 13],
            receiver_bits: [7, 8],
            has_inferred_bit: 14,
        });
        // ScopeInfo 的数值域各占一个 slot：9.x–12.x 是 Smi（值在高 32 位），
        // ≤8.4 与 13.x 是**裸 int32**（`FOR_EACH_SCOPE_INFO_NUMERIC_FIELD` 的
        // `inline int name() const`）。原来一律按 Smi 读 —— 老族于是全都读不出来，
        // `scope_name_slots` 直接返回 None，函数名/形参名全丢（node14 产物叫 `_anon_4`）。
        // 数值域起点随版本变：
        //   ≤8.4：ScopeInfo 是 FixedArray，头两格是 map+length → Flags 在**槽 2**、
        //         ParameterCount 槽 3、ContextLocalCount 槽 4，变量区从**槽 5** 起
        //         （实测 node14：槽 5 正是函数名 `String:target` 的根引用）。
        //   9.x+ ：Flags 在槽 1（本代码长期验证过的路径）。
        let legacy = self.table.v8.starts_with('8')
            || self.table.v8.starts_with('7')
            || self.table.v8.starts_with('6');
        let base = if legacy { 2 } else { 1 };
        let flags = self.num_field(id, base, legacy || cfg.flags_smi).unwrap_or(0) as u64;

        let has_saved = (flags >> cfg.saved_class_bit) & 1 == 1;
        let function_var = ((flags >> cfg.function_variable_bits[0])
            & ((1 << (cfg.function_variable_bits[1] - cfg.function_variable_bits[0] + 1)) - 1))
            as u32;
        let has_inferred = (flags >> cfg.has_inferred_bit) & 1 == 1;
        let receiver_var = ((flags >> cfg.receiver_bits[0])
            & ((1 << (cfg.receiver_bits[1] - cfg.receiver_bits[0] + 1)) - 1)) as u32;
        let has_receiver = matches!(receiver_var, 1 | 2);

        if std::env::var("JSCD_DBG_SFI").is_ok() {
            eprintln!(
                "[sfi]   id={id} flags={flags:#x} function_var={function_var} has_inferred={has_inferred} has_saved={has_saved} has_receiver={has_receiver} len={}",
                self.cache.array_len(id)
            );
        }
        if !cfg.position_info_early {
            // 槽位 = (变量区起点) + 2n + saved + receiver；起点 ≤8.4 为 5、9.x–12.x 为 4
            let Some(n) = self.num_field(id, base + 2, legacy || cfg.flags_smi) else {
                return (None, None);
            };
            let vpart = if legacy { 5 } else { 4 };
            let mut cursor =
                vpart + 2 * n as usize + has_saved as usize + has_receiver as usize;
            // V8 `ScopeInfo::HasFunctionName()`（8.4 到 13.x 都是同一条：
            //   `return VariableAllocationInfo::NONE != FunctionVariableBits::decode(Flags());`）
            // —— 只有 NONE(0) 表示"没有名字槽"；UNUSED(3) 只是函数变量没被用到，槽位照样
            // 保留（里面是 `kNoSharedNameSentinel`，一个 Smi → 序列化成 raw 字）。
            // 所以判定交给**槽里的值**：是字符串才算名字（`scope_function_name` 对非字符串的
            // Ref/Raw 一律返回空串），非字符串就走 inferred / 匿名。
            // 早先按"必须 STACK/CONTEXT"过滤，把 node14 的真名一起丢了 —— closure 的
            // `target` 在 flags 里就是 function_var=3，产物成了 `_anon_4` → target-missing。
            let function_name = if function_var != 0 {
                let slot = cursor;
                cursor += 2;
                Some(slot)
            } else {
                None
            };
            let inferred = if has_inferred { Some(cursor) } else { None };
            return (function_name, inferred);
        }

        // 13.x：flags+padding(ts+8) | parameter_count(ts+8) | context_local_count(ts+16)
        let param_off = ts + 8;
        let clc_off = ts + 16;
        let _ = param_off;
        let Some(n) = self
            .cache
            .raw_at(id, clc_off, ts)
            .and_then(|d| self.decode_smi_bytes(d))
        else {
            return (None, None);
        };
        let n = n as usize;
        let mut off = clc_off + ts; // 变长区起点（字节）
        off += 2 * ts; // position_info（2 个 Smi）
        let scope_type = flags & 0xF;
        if scope_type == 3 {
            off += ts; // module_variable_count
        }
        if n < cfg.max_inlined_names {
            off += n * ts; // context_local_names
        } else {
            off += ts; // context_local_names_hashtable
        }
        off += n * ts; // context_local_infos
        if has_saved {
            off += ts;
        }
        let function_name = if function_var != 0 {
            let slot = off / ts;
            off += 2 * ts;
            Some(slot)
        } else {
            None
        };
        let inferred = if has_inferred { Some(off / ts) } else { None };
        (function_name, inferred)
    }

    fn scope_function_name(&self, id: ObjId) -> String {
        if std::env::var("JSCD_DBG_SFI").is_ok() {
            let (a, b) = self.scope_name_slots(id);
            eprintln!(
                "[sfi] scope={id} name_slot={a:?} inferred_slot={b:?} v0={:?} v1={:?}",
                a.and_then(|s| self.cache.slot_at(id, s)),
                b.and_then(|s| self.cache.slot_at(id, s))
            );
        }
        match self.scope_name_slots(id).0 {
            Some(slot) => match self.cache.slot_at(id, slot) {
                Some(SlotValue::Ref(r)) => self.name_from_ref(*r),
                _ => String::new(),
            },
            None => String::new(),
        }
    }

    fn scope_inferred_name(&self, id: ObjId) -> String {
        match self.scope_name_slots(id).1 {
            Some(slot) => match self.cache.slot_at(id, slot) {
                Some(SlotValue::Ref(r)) => self.name_from_ref(*r),
                _ => String::new(),
            },
            None => String::new(),
        }
    }

    /// 解 8/4 字节 Smi（无压缩：值在高 32 位；压缩：低 32 位带 tag）。
    fn decode_smi_bytes(&self, d: &[u8]) -> Option<i64> {
        if d.len() == 8 {
            Some((read_u64(d) >> 32) as u32 as i32 as i64)
        } else if d.len() == 4 {
            let raw = u32::from_le_bytes(d.try_into().ok()?);
            if raw & 1 == 0 {
                None
            } else {
                Some(((raw as i32) >> 1) as i64)
            }
        } else {
            None
        }
    }

    /// 读对象内某个 tagged 槽的 Smi 值（无压缩：高 32 位；压缩：低 32 位带 tag）。
    fn smi_slot(&self, id: ObjId, slot: usize) -> Option<i64> {
        let ts = self.layout.tagged_size;
        let d = self.cache.raw_at(id, slot * ts, ts)?;
        if ts == 8 {
            Some((read_u64(d) >> 32) as u32 as i32 as i64)
        } else {
            let raw = u32::from_le_bytes(d.try_into().ok()?);
            Some(((raw as i32) >> 1) as i64)
        }
    }

    fn render_sfi(&self, id: ObjId, name: &str, out: &mut String) -> Result<(), String> {
        // function_data 槽（9.x–12.x 单槽；13.6 起 trusted/untrusted 拆分，取指向 BCA 的那个）
        let mut bca_id = None;
        for slot in self.sfi_function_data_slots() {
            if let Some(SlotValue::Ref(Ref::Object(b))) = self.cache.slot_at(id, slot) {
                if self.cache.obj(*b).ty.is(self.table, "BytecodeArray") {
                    bca_id = Some(*b);
                    break;
                }
            }
        }
        let Some(bca_id) = bca_id else {
            return Ok(()); // 未编译（UncompiledData）——留给 functions 子命令展示
        };
        let ba_layout = self
            .table
            .bytecode_array
            .clone()
            .unwrap_or_else(|| crate::tables::BytecodeArrayLayout::fallback(self.layout.tagged_size));
        let header = ba_layout.header_size;
        let obj = self.cache.obj(bca_id);
        let bytecode_len = self
            .cache
            .raw_at(bca_id, self.layout.tagged_size, self.layout.tagged_size)
            .map(|d| read_u64(d) >> 32)
            .unwrap_or(0) as usize;
        let frame_size = ba_layout
            .off("frame_size")
            .and_then(|o| self.cache.raw_at(bca_id, o, 4))
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()))
            .unwrap_or(0);
        // parameter_size 是字节数；V8 的 parameter_count() = parameter_size / kSystemPointerSize
        let parameter_size = ba_layout
            .off("parameter_size")
            .and_then(|o| self.cache.raw_at(bca_id, o, 4))
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()) as i32)
            .unwrap_or(0);
        // parameter_size 语义随版本变：≤12 存字节数，13.x 起直接是计数
        let parameter_count = if self
            .table
            .parameter_count
            .map(|c| c.direct)
            .unwrap_or(false)
        {
            // 13.x：字段是 uint16，直接就是计数
            parameter_size & 0xFFFF
        } else {
            parameter_size / 8
        };
        // osr 字段名随版本变（osr_loop_nesting_level / osr_urgency_and_install_target）；11.3+ 已移除
        let osr = ba_layout
            .off("osr_loop_nesting_level")
            .or_else(|| ba_layout.off("osr_urgency_and_install_target"))
            .and_then(|o| self.cache.raw_at(bca_id, o, 1))
            .map(|d| d[0])
            .unwrap_or(0);
        let age = ba_layout
            .off("bytecode_age")
            .and_then(|o| self.cache.raw_at(bca_id, o, 1))
            .map(|d| d[0])
            .unwrap_or(0);
        let code = self
            .cache
            .raw_at(bca_id, header, bytecode_len)
            .unwrap_or_default();

        let decoder = Decoder::new(self.table, self.layout, parameter_count);
        let instrs = decoder.decode(code).map_err(|e| {
            format!("decode bytecode of '{}' ({} bytes): {e}", name, code.len())
        })?;
        // V8: register_count() = frame_size / kSystemPointerSize
        let register_count = frame_size / 8;

        let _ = writeln!(
            out,
            "[generated bytecode for function: {name} (jscd <SharedFunctionInfo {name}>)]"
        );
        let _ = writeln!(out, "Bytecode length: {bytecode_len}");
        let _ = writeln!(out, "Parameter count {parameter_count}");
        let _ = writeln!(out, "Register count {register_count}");
        let _ = writeln!(out, "Frame size {frame_size}");
        let _ = writeln!(out, "OSR nesting level: {osr}");
        let _ = writeln!(out, "Bytecode Age: {age}");
        for ins in &instrs {
            let hex = ins
                .bytes
                .iter()
                .map(|b| format!("{b:02x} "))
                .collect::<String>();
            let ops = ins
                .operands
                .iter()
                .map(|o| decoder.render_operand(o))
                .collect::<Vec<_>>()
                .join(", ");
            // 跳转目标：V8 打印 " (0xaddr @ target)"；我们无地址，用同样形状的 (jscd @ target)
            let jump = self
                .jump_target(bca_id, ins)
                .map(|t| format!(" (jscd @ {t})"))
                .unwrap_or_default();
            // switch 跳转表：{ case: @target, ... }（V8 BytecodeArray::Disassemble 同形）
            let switch = self
                .jump_table(bca_id, ins)
                .map(|entries| {
                    let body = entries
                        .iter()
                        .map(|(c, t)| format!(" {c}: @{t}"))
                        .collect::<Vec<_>>()
                        .join(",");
                    format!(" {{{body} }}")
                })
                .unwrap_or_default();
            let _ = writeln!(
                out,
                "{:>10} @ {:>4} : {:<18} {}{}{}{}",
                "",
                ins.offset,
                hex.trim_end(),
                ins.name,
                if ops.is_empty() { String::new() } else { format!(" {ops}") },
                jump,
                switch
            );
            let _ = &switch;
        }
        self.render_constant_pool(bca_id, out);
        self.render_byte_array(
            "Handler Table",
            self.cache.slot_at(bca_id, self.bca_handler_table_slot()).and_then(|v| v.as_ref()),
            out,
        );
        self.render_byte_array(
            "Source Position Table",
            self.cache
                .slot_at(bca_id, self.bca_source_position_slot())
                .and_then(|v| v.as_ref()),
            out,
        );
        let _ = writeln!(out);
        let _ = obj;
        Ok(())
    }

    fn render_byte_array(&self, label: &str, r: Option<Ref>, out: &mut String) {
        match r {
            Some(Ref::Object(id)) if self.cache.obj(id).ty.is(self.table, "ByteArray") => {
                // 长度在 tag 槽里，但**落在哪半**随版本变（9.x–12.x 在高 32 位，
                // 13.x 搬到低 32 位）→ 两半都取，选像长度的那个（≤ 对象字节数）。
                let obj_bytes = self.cache.obj(id).byte_size;
                let word = self
                    .cache
                    .raw_at(id, self.layout.tagged_size, 8.min(self.layout.tagged_size));
                let len = match word {
                    Some(d) if d.len() == 8 => {
                        let w = read_u64(d);
                        let hi = (w >> 32) as u32 as usize;
                        let lo = (w & 0xffff_ffff) as u32 as usize;
                        if hi <= obj_bytes && (lo > obj_bytes || hi >= lo) {
                            hi
                        } else {
                            lo
                        }
                    }
                    Some(d) if d.len() == 4 => {
                        u32::from_le_bytes(d.try_into().unwrap()) as usize
                    }
                    _ => 0,
                };
                let _ = writeln!(out, "{label} (size = {len})");
            }
            Some(Ref::Root(i)) => {
                let n = self.table.root_name(i).unwrap_or_default().to_string();
                if n.contains("empty_byte_array") || n.contains("EmptyByteArray") {
                    let _ = writeln!(out, "{label} (size = 0)");
                } else {
                    let _ = writeln!(out, "{label} (size = ?)");
                }
            }
            _ => {
                let _ = writeln!(out, "{label} (size = 0)");
            }
        }
    }

    fn render_constant_pool(&self, bca_id: ObjId, out: &mut String) {
        // 常量池：FixedArray（map + length Smi + elements，Smi 与指针交错在 raw/ref 单元里）
        let pool = self
            .cache
            .slot_at(bca_id, self.bca_constant_pool_slot())
            .and_then(|v| v.as_ref())
            .and_then(|r| self.cache.ref_object(r));
        let Some(pool_id) = pool else {
            let _ = writeln!(out, "Constant pool (size = 0)");
            return;
        };
        let entries = self.fixed_array_entries(pool_id);
        let _ = writeln!(out, "Constant pool (size = {})", entries.len());
        for (i, e) in entries.iter().enumerate() {
            let _ = writeln!(out, "{:>12}: {}", i, e);
        }
    }

    /// 跳转目标（对齐 V8 BytecodeArrayIterator::GetJumpTargetOffset）。
    ///
    /// - 立即数形式：目标 = 指令自身偏移 + 相对量（JumpLoop 取负，不是"下一条"）
    /// - `*Constant` 形式：相对量取自常量池里的 Smi
    fn jump_target(&self, bca_id: ObjId, ins: &Instr) -> Option<usize> {
        // V8: GetAbsoluteOffset(rel) = current_offset + rel + prefix_size（Wide 前缀占 1 字节）
        let prefix = if ins.scale > 1 { 1 } else { 0 };
        let here = ins.offset + prefix;
        let base = ins.name.trim_end_matches(".Wide").trim_end_matches(".ExtraWide");
        let is_constant = base.ends_with("Constant");
        let rel: i64 = if is_constant {
            let idx = match ins.operands.first()? {
                Operand::Idx(v) => *v as usize,
                _ => return None,
            };
            let pool = self
                .cache
                .slot_at(bca_id, self.bca_constant_pool_slot())
                .and_then(|v| v.as_ref())
                .and_then(|r| self.cache.ref_object(r))?;
            self.cache.array_elem(pool, idx).and_then(|e| e.as_smi())?
        } else {
            match ins.operands.first()? {
                Operand::Idx(v) => *v as i64,
                Operand::Imm(v) => *v,
                _ => return None,
            }
        };
        match base {
            "Jump" | "JumpConstant" | "JumpIfTrue" | "JumpIfTrueConstant" | "JumpIfFalse"
            | "JumpIfFalseConstant" | "JumpIfToBooleanTrue" | "JumpIfToBooleanTrueConstant"
            | "JumpIfToBooleanFalse" | "JumpIfToBooleanFalseConstant" | "JumpIfNull"
            | "JumpIfNullConstant" | "JumpIfNotNull" | "JumpIfNotNullConstant"
            | "JumpIfUndefined" | "JumpIfUndefinedConstant" | "JumpIfUndefinedOrNull"
            | "JumpIfUndefinedOrNullConstant" | "JumpIfNotUndefined"
            | "JumpIfNotUndefinedConstant" | "JumpIfJSReceiver" | "JumpIfJSReceiverConstant"
            | "JumpIfNotHole" | "JumpIfNotHoleConstant" | "JumpIfReferenceError"
            | "JumpIfReferenceErrorConstant" | "JumpIfNotReferenceError"
            | "JumpIfNotReferenceErrorConstant" => {
                Some((here as i64 + rel) as usize)
            }
            "JumpLoop" | "JumpLoopConstant" => {
                (ins.offset as i64 + prefix as i64).checked_sub(rel).map(|v| v as usize)
            }
            _ => None,
        }
    }

    /// switch 跳转表：常量池 [start, start+size) 的 Smi 项，目标 = 指令偏移 + Smi。
    fn jump_table(&self, bca_id: ObjId, ins: &Instr) -> Option<Vec<(i32, usize)>> {
        // SwitchOnSmiNoFeedback: [Idx table_start, UImm size, Imm case_base]
        // SwitchOnGeneratorState: [Reg, Idx table_start, UImm size]，case_base = 0
        let (start_idx, size_idx, base_idx, base_fixed) = match ins.name.as_str() {
            "SwitchOnSmiNoFeedback" => (0usize, 1usize, Some(2usize), 0i32),
            "SwitchOnGeneratorState" => (1, 2, None, 0),
            _ => return None,
        };
        let table_start = match ins.operands.get(start_idx)? {
            Operand::Idx(v) => *v as usize,
            _ => return None,
        };
        let table_size = match ins.operands.get(size_idx)? {
            Operand::Idx(v) => *v as usize,
            Operand::Imm(v) => *v as usize,
            _ => return None,
        };
        let case_base = match base_idx {
            Some(i) => match ins.operands.get(i)? {
                Operand::Imm(v) => *v as i32,
                Operand::Idx(v) => *v as i32,
                _ => return None,
            },
            None => base_fixed,
        };
        let pool = self
            .cache
            .slot_at(bca_id, self.bca_constant_pool_slot())
            .and_then(|v| v.as_ref())
            .and_then(|r| self.cache.ref_object(r))?;
        let mut out = Vec::new();
        for i in 0..table_size {
            // V8 迭代器跳过非 Smi 槽，但 case 值随槽位递增
            if let Some(Elem::Smi(v)) = self.cache.array_elem(pool, table_start + i) {
                // 同样走 GetAbsoluteOffset（含 Wide 前缀字节）
                let prefix = if ins.scale > 1 { 1 } else { 0 };
                out.push((case_base + i as i32, ins.offset + prefix + v as usize));
            }
        }
        Some(out)
    }

    /// 供 CLI 使用的公开入口。
    pub fn array_elem_public(&self, id: ObjId, index: usize) -> Option<Elem<'a>> {
        self.cache.array_elem(id, index)
    }

    /// parameter_count 是否直接是计数（13.x+）。
    pub fn parameter_count_direct(&self) -> bool {
        self.table.parameter_count.map(|c| c.direct).unwrap_or(false)
    }

    /// FixedArray 元素（按字节偏移取值；length 槽在 offset=ts，元素 i 在 (2+i)*ts）。
    fn array_elem(&self, id: ObjId, index: usize) -> Option<Elem<'a>> {
        self.cache.array_elem(id, index)
    }

    /// FixedArray 元素数。
    pub fn fixed_array_len(&self, id: ObjId) -> usize {
        self.cache.array_len(id)
    }

    /// FixedArray 元素展开（Smi / 引用，按元素序）。
    pub fn fixed_array_entries(&self, id: ObjId) -> Vec<String> {
        let len = self.fixed_array_len(id);
        (0..len)
            .map(|i| match self.cache.array_elem(id, i) {
                Some(Elem::Smi(v)) => v.to_string(),
                Some(Elem::Ref(r)) => self.describe_ref(&r),
                Some(Elem::Bytes(b)) => format!("<raw {}>", hex(b)),
                None => "<hole>".into(),
            })
            .collect()
    }

    /// FixedArray 的数值元素（Smi → Some，其余 → None），用于跳转表。
    pub fn fixed_array_smis(&self, id: ObjId) -> Vec<Option<i64>> {
        let len = self.fixed_array_len(id);
        (0..len)
            .map(|i| self.cache.array_elem(id, i).and_then(|e| e.as_smi()))
            .collect()
    }

    /// 引用 → 可读描述（对齐 V8 printer 的常量池样式）。
    pub fn describe_ref(&self, r: &Ref) -> String {
        match r {
            Ref::Object(id) => {
                let o = self.cache.obj(*id);
                match o.ty.name(self.table).as_ref() {
                    t if t.contains("String") => self
                        .string_value(*id)
                        .map(|s| format!("<String[{}]: #{} >", s.chars().count(), s))
                        .unwrap_or_else(|| "<String>".into()),
                    "SharedFunctionInfo" => {
                        format!("<SharedFunctionInfo {}>", self.sfi_name(*id))
                    }
                    "HeapNumber" => {
                        let v = self
                            .cache
                            .raw_at(*id, self.layout.tagged_size, 8)
                            .map(|d| f64::from_le_bytes(d.try_into().unwrap()))
                            .unwrap_or(f64::NAN);
                        format!("<HeapNumber {v}>")
                    }
                    "ScopeInfo" => "<ScopeInfo>".into(),
                    "FixedArray" | "FixedCOWArray" => format!("<FixedArray[{}]>", self.fixed_array_entries(*id).len()),
                    "ObjectBoilerplateDescription" => "<ObjectBoilerplateDescription>".into(),
                    "ArrayBoilerplateDescription" => "<ArrayBoilerplateDescription>".into(),
                    "ByteArray" | "EmptyByteArray" => "<ByteArray>".into(),
                    "BigInt" => self
                        .bigint_value(*id)
                        .map(|v| format!("<BigInt {v}>"))
                        .unwrap_or_else(|| "<BigInt>".into()),
                    other => format!("<{other}>"),
                }
            }
            Ref::Root(i) => {
                let name = self
                    .table
                    .roots
                    .get(*i)
                    .cloned()
                    .unwrap_or_else(|| format!("root#{i}"));
                match name.as_str() {
                    n if n.starts_with("String:") => format!("<String: {}>", &n[7..]),
                    n if n.starts_with("Symbol:") => format!("<Symbol: {}>", &n[7..]),
                    "undefined_value" => "<undefined>".into(),
                    "null_value" => "<null>".into(),
                    "true_value" => "<true>".into(),
                    "false_value" => "<false>".into(),
                    "the_hole_value" => "<the_hole>".into(),
                    "uninitialized_value" => "<uninitialized>".into(),
                    "empty_fixed_array" => "<EmptyFixedArray>".into(),
                    "empty_string" => "<String[0]: #>".into(),
                    other => format!("<{other}>"),
                }
            }
            Ref::Attached(0) => {
                let len = self.attached_source_len();
                format!("<String[{len}]: #(source placeholder)>")
            }
            Ref::Attached(i) => format!("<Attached({i})>"),
            Ref::RoRef(c, o) => format!("<ro:{c}/{o}>"),
        }
    }

    /// 源码占位字符串长度（来自头部 source_hash，由调用方注入）
    fn attached_source_len(&self) -> u32 {
        self.source_len
    }

    pub fn string_value(&self, id: ObjId) -> Option<String> {
        let obj = self.cache.obj(id);
        // 字符串布局（真机实证，含压缩/非压缩家族一致）：
        //   @0 map | @8 hash_field(int32) | @12 length(int32) | @16 chars
        let length = self
            .cache
            .raw_at(id, 12, 4)
            .map(|d| u32::from_le_bytes(d.try_into().unwrap()) as usize)?;
        let is_one_byte = match obj.ty {
            crate::serializer::Ty::Str(crate::serializer::StrKind::OneByte) => true,
            crate::serializer::Ty::Str(crate::serializer::StrKind::TwoByte) => false,
            _ => obj.ty.name(self.table).contains("OneByte"),
        };
        let chars_off = 16;
        let d = self.cache.raw_at(id, chars_off, length)?;
        if is_one_byte {
            Some(String::from_utf8_lossy(d).into_owned())
        } else {
            let u16s: Vec<u16> = d
                .chunks(2)
                .map(|c| u16::from_le_bytes([c[0], *c.get(1).unwrap_or(&0)]))
                .collect();
            Some(String::from_utf16_lossy(&u16s))
        }
    }

    fn bigint_value(&self, id: ObjId) -> Option<String> {
        // BigInt：map + length(Smi) + 数字（64 位块，补码）
        let ts = self.layout.tagged_size;
        let len = self
            .cache
            .raw_at(id, ts, ts)
            .map(|d| read_u64(d) >> 32)? as usize;
        if len == 0 {
            return Some("0".into());
        }
        let bytes = self.cache.raw_at(id, 2 * ts, len * 8)?;
        let mut v: i128 = 0;
        for (i, chunk) in bytes.chunks(8).enumerate() {
            let word = u64::from_le_bytes(chunk.try_into().ok()?);
            v |= (word as i128) << (64 * i);
        }
        // 最高位为符号位
        let bits = len * 64;
        if bits < 128 && (v >> (bits - 1)) & 1 == 1 {
            v -= 1i128 << bits;
        }
        Some(v.to_string())
    }

    /// 供 CLI 注入源码长度（attached ref 0 的展示）
    pub fn with_source_len(mut self, len: u32) -> Self {
        self.source_len = len;
        self
    }
}



/// Ref → 名字字符串（字符串对象 / 根名字），供反编译与 ScopeInfo 读取复用。
pub fn name_of_ref(cache: &CodeCache<'_>, table: &VersionTable, r: Ref) -> Option<String> {
    match r {
        Ref::Object(id) => {
            let o = cache.obj(id);
            if o.ty.is_string(table) {
                // 复用 Disassembler 的字符串解码路径
                let ts = table.tagged_size as usize;
                let len = cache.raw_at_ts(id, 12, 4, ts).map(|d| u32::from_le_bytes(d.try_into().unwrap()) as usize)?;
                let one_byte = matches!(
                    o.ty,
                    crate::serializer::Ty::Str(crate::serializer::StrKind::OneByte)
                );
                let d = cache.raw_at_ts(id, 16, if one_byte { len } else { len * 2 }, ts)?;
                Some(if one_byte {
                    String::from_utf8_lossy(d).into_owned()
                } else {
                    let u16s: Vec<u16> = d.chunks(2).map(|c| u16::from_le_bytes([c[0], *c.get(1).unwrap_or(&0)])).collect();
                    String::from_utf16_lossy(&u16s)
                })
            } else {
                None
            }
        }
        Ref::Root(i) => table.root_name(i).map(|n| {
            match n {
                // 这些 root 作为"名字"出现时应为空（CamelName 形态来自 roots.h 列表）
                "empty_string" | "EmptyString" | "undefined_value" | "UndefinedValue"
                | "uninitialized_value" | "UninitializedValue" | "the_hole_value"
                | "TheHoleValue" => String::new(),
                other => other
                    .strip_prefix("String:")
                    .or_else(|| other.strip_prefix("Symbol:"))
                    .unwrap_or(other)
                    .to_string(),
            }
        }),
        _ => None,
    }
}

fn read_u64(d: &[u8]) -> u64 {
    let mut v = 0u64;
    for (i, b) in d.iter().take(8).enumerate() {
        v |= (*b as u64) << (8 * i);
    }
    v
}

/// Smi 解码：无压缩（ts=8）值在高 32 位；压缩（ts=4）值在低 32 位且末位为 1。
fn decode_smi(group: &[u8]) -> Option<i64> {
    if group.len() == 8 {
        let raw = read_u64(group);
        let v = (raw >> 32) as u32;
        if v == 0 && raw != 0 {
            return None;
        }
        Some((v as i32) as i64)
    } else if group.len() == 4 {
        let raw = u32::from_le_bytes(group.try_into().ok()?);
        if raw & 1 == 0 {
            return None;
        }
        Some(((raw as i32) >> 1) as i64)
    } else {
        None
    }
}

fn hex(d: &[u8]) -> String {
    d.iter().map(|b| format!("{b:02x}")).collect::<Vec<_>>().join("")
}

#[allow(dead_code)]
fn max_register(instrs: &[Instr]) -> Option<i32> {
    let mut max: Option<i32> = None;
    for ins in instrs {
        for op in &ins.operands {
            let idx = match op {
                Operand::Reg(i) => Some(*i),
                Operand::RegList { first, count } => Some(if *count > 0 {
                    first + (*count as i32) - 1
                } else {
                    *first
                }),
                _ => None,
            };
            if let Some(i) = idx {
                if i >= 0 {
                    max = Some(max.map_or(i, |m: i32| m.max(i)));
                }
            }
        }
    }
    max
}